class Countries {
  String name;
  String isoCode;

  Countries({this.name, this.isoCode});

  Countries.fromJson(Map json)
      : name = json['name'],
        isoCode = json['isoCode'];

  Map toJson() => {'name': name, 'isoCode': isoCode};
}

List<Countries> countriesl = [
  Countries(isoCode: 'af', name: 'Afghanistan'),
  Countries(isoCode: 'al', name: 'Albania'),
  Countries(isoCode: 'dz', name: 'Algeria'),
  Countries(isoCode: 'as', name: 'American Samoa'),
  Countries(isoCode: 'as', name: 'American Samoa'),
  Countries(isoCode: 'af', name: 'Andorra'),
  Countries(isoCode: 'ad', name: 'Afghanistan'),
  Countries(name: 'Angola', isoCode: 'ao'),
  Countries(name: 'Anguilla', isoCode: 'ai'),
  Countries(name: 'Antarctica', isoCode: 'aq'),
  Countries(name: 'Antigua and Barbuda', isoCode: 'ag'),
  Countries(name: 'Argentina', isoCode: 'ar'),
  Countries(name: 'Armenia', isoCode: 'am'),
  Countries(name: 'Aruba', isoCode: 'aw'),
  Countries(name: 'Australia', isoCode: 'au'),
  Countries(name: 'Austria', isoCode: 'at'),
  Countries(name: 'Azerbaijan', isoCode: 'az'),
  Countries(name: 'Bahamas', isoCode: 'bs'),
  Countries(name: 'Bahrain', isoCode: 'bh'),
  Countries(name: 'Bangladesh', isoCode: 'bd'),
  Countries(name: 'Barbados', isoCode: 'bb'),
  Countries(name: 'Belarus', isoCode: 'by'),
  Countries(name: 'Belgium', isoCode: 'be'),
  Countries(name: 'Belize', isoCode: 'bz'),
  Countries(name: 'Benin', isoCode: 'bj'),
  Countries(name: 'Bermuda', isoCode: 'bm'),
  Countries(name: 'Bhutan', isoCode: 'bt'),
  Countries(name: 'Bolivia', isoCode: 'no'),
  Countries(name: 'Bonaire, Sint Eustatius and Saba', isoCode: 'bq'),
  Countries(name: 'Bosnia and Herzegovina', isoCode: 'ba'),
  Countries(name: 'Botswana', isoCode: 'bw'),
  Countries(name: 'Bouvet Island', isoCode: 'bv'),
  Countries(name: 'Brazil', isoCode: 'br'),
  Countries(name: 'British Indian Ocean Territory', isoCode: 'io'),
  Countries(name: 'Brunei Darussalam', isoCode: 'bn'),
  Countries(name: 'Bulgaria', isoCode: 'bg'),
  Countries(name: 'Burkina Faso', isoCode: 'bf'),
  Countries(name: 'Burundi', isoCode: 'bi'),
  Countries(name: 'Cabo Verde ', isoCode: 'cv'),
  Countries(name: 'Cambodia', isoCode: 'cm'),
  Countries(name: 'Canada', isoCode: 'ca'),
  Countries(name: 'Cayman Islands', isoCode: 'ky'),
  Countries(name: 'Central African Republic', isoCode: 'by'),
  Countries(name: 'Chad', isoCode: 'td'),
  Countries(name: 'Chile', isoCode: 'cl'),
  Countries(name: 'China', isoCode: 'cn'),
  Countries(name: 'Christmas Island', isoCode: 'cx'),
  Countries(name: 'Colombia', isoCode: 'co'),
  Countries(name: 'Comoros ', isoCode: 'km'),
  Countries(name: 'Congo', isoCode: 'cd'),
  Countries(name: 'Cook Islands', isoCode: 'ck'),
  Countries(name: 'Costa Rica', isoCode: 'cr'),
  Countries(name: 'Croatia', isoCode: 'hr'),
  Countries(name: 'Cuba', isoCode: 'cu'),
  Countries(name: 'Curaçao', isoCode: 'cw'),
  Countries(name: 'Cyprus', isoCode: 'cy'),
  Countries(name: 'Czechia', isoCode: 'cz'),
  Countries(name: 'Denmark', isoCode: 'dk'),
  Countries(name: 'Djibouti', isoCode: 'dj'),
  Countries(name: 'Dominica ', isoCode: 'dm'),
  Countries(name: 'Dominican Republic', isoCode: 'do'),
  Countries(name: 'Ecuador', isoCode: 'ec'),
  Countries(name: 'Egypt', isoCode: 'eg'),
  Countries(name: 'El Salvador', isoCode: 'sv'),
  Countries(name: 'Equatorial Guinea', isoCode: 'gq'),
  Countries(name: 'Eritrea', isoCode: 'er'),
  Countries(name: 'Estonia', isoCode: 'ee'),
  Countries(name: 'Eswatini', isoCode: 'sz'),
  Countries(name: 'Ethiopia', isoCode: 'et'),
  Countries(name: 'Falkland Islands', isoCode: 'fk'),
  Countries(name: 'Faroe Islands', isoCode: 'fo'),
  Countries(name: 'Fiji', isoCode: 'fj'),
  Countries(name: 'Finland', isoCode: 'fi'),
  Countries(name: 'France', isoCode: 'fr'),
  Countries(name: 'French Guiana', isoCode: 'gf'),
  Countries(name: 'French Polynesia', isoCode: 'pf'),
  Countries(name: 'French Southern Territories', isoCode: 'tf'),
  Countries(name: 'Gabon', isoCode: 'ga'),
  Countries(name: 'Gambia', isoCode: 'de'),
  Countries(name: 'Germany', isoCode: 'dm'),
  Countries(name: 'Ghana', isoCode: 'gh'),
  Countries(name: 'Gibraltar', isoCode: 'gi'),
  Countries(name: 'Greece', isoCode: 'gr'),
  Countries(name: 'Greenland', isoCode: 'gl'),
  Countries(name: 'Grenada', isoCode: 'gd'),
  Countries(name: 'Guadeloupe', isoCode: 'gp'),
  Countries(name: 'Guam', isoCode: 'gu'),
  Countries(name: 'Guatemala', isoCode: 'gt'),
  Countries(name: 'Guernsey', isoCode: 'gg'),
  Countries(name: 'Guinea', isoCode: 'gn'),
  Countries(name: 'Guinea-Bissau', isoCode: 'gw'),
  Countries(name: 'Guyana', isoCode: 'gy'),
  Countries(name: 'Haiti', isoCode: 'ht'),
  Countries(name: 'Heard Island and McDonald Islands', isoCode: 'hm'),
  Countries(name: 'Honduras', isoCode: 'hn'),
  Countries(name: 'Hong Kong', isoCode: 'hk'),
  Countries(name: 'Hungary', isoCode: 'hu'),
  Countries(name: 'Iceland', isoCode: 'is'),
  Countries(name: 'Indonesia', isoCode: 'id'),
  Countries(name: 'Iran', isoCode: 'ir'),
  Countries(name: 'Iraq', isoCode: 'iq'),
  Countries(name: 'Ireland', isoCode: 'ie'),
  Countries(name: 'Isle of Man', isoCode: 'im'),
  Countries(name: 'Israel', isoCode: 'il'),
  Countries(name: 'Italy', isoCode: 'it'),
  Countries(name: 'Jamaica', isoCode: 'jm'),
  Countries(name: 'Japan', isoCode: 'jp'),
  Countries(name: 'Jersey', isoCode: 'je'),
  Countries(name: 'Jordan', isoCode: 'jo'),
  Countries(name: 'Kazakhstan', isoCode: 'kz'),
  Countries(name: 'Kenya', isoCode: 'ke'),
  Countries(name: 'Kiribati', isoCode: 'ki'),
  Countries(name: 'Kuwait', isoCode: 'kw'),
  Countries(name: 'Kyrgyzstan', isoCode: 'kg'),
  Countries(name: 'Laos', isoCode: 'la'),
  Countries(name: 'Latvia', isoCode: 'lv'),
  Countries(name: 'Lebanon', isoCode: 'lb'),
  Countries(name: 'Lesotho', isoCode: 'ls'),
  Countries(name: 'Liberia', isoCode: 'lr'),
  Countries(name: 'Libya', isoCode: 'ly'),
  Countries(name: 'Liechtenstein', isoCode: 'li'),
  Countries(name: 'Lithuania', isoCode: 'lt'),
  Countries(name: 'Luxembourg', isoCode: 'lu'),
  Countries(name: 'Macao', isoCode: 'mo'),
  Countries(name: 'Madagascar', isoCode: 'mg'),
  Countries(name: 'Malawi', isoCode: 'mw'),
  Countries(name: 'Malaysia', isoCode: 'my'),
  Countries(name: 'Maldives', isoCode: 'mv'),
  Countries(name: 'Mali', isoCode: 'ml'),
  Countries(name: 'Malta ', isoCode: 'mt'),
  Countries(name: 'Marshall Islands', isoCode: 'mh'),
  Countries(name: 'Martinique', isoCode: 'mq'),
  Countries(name: 'Mauritania', isoCode: 'mr'),
  Countries(name: 'Mauritius', isoCode: 'mu'),
  Countries(name: 'Mayotte', isoCode: 'yt'),
  Countries(name: 'Mexico', isoCode: 'mx'),
  Countries(name: 'Micronesia', isoCode: 'fm'),
  Countries(name: 'Moldova', isoCode: 'md'),
  Countries(name: 'Monaco ', isoCode: 'mc'),
  Countries(name: 'Mongolia', isoCode: 'mn'),
  Countries(name: 'Montenegro', isoCode: 'me'),
  Countries(name: 'Montserrat', isoCode: 'ms'),
  Countries(name: 'Morocco', isoCode: 'ma'),
  Countries(name: 'Mozambique', isoCode: 'mz'),
  Countries(name: 'Myanmar', isoCode: 'na'),
  Countries(name: 'Nauru', isoCode: 'nr'),
  Countries(name: 'Nepal', isoCode: 'np'),
  Countries(name: 'Netherlands ', isoCode: 'nl'),
  Countries(name: 'New Caledonia ', isoCode: 'nc'),
  Countries(name: 'New Zealand', isoCode: 'nz'),
  Countries(name: 'Nicaragua', isoCode: 'ni'),
  Countries(name: 'Niger', isoCode: 'ne'),
  Countries(name: 'Nigeria', isoCode: 'ng'),
  Countries(name: 'Niue', isoCode: 'nu'),
  Countries(name: 'Norfolk Island', isoCode: 'nf'),
  Countries(name: 'North Korea', isoCode: 'kp'),
  Countries(name: 'Northern Mariana Islands', isoCode: 'mp'),
  Countries(name: 'Norway', isoCode: 'no'),
  Countries(name: 'Oman', isoCode: 'om'),
  Countries(name: 'Pakistan', isoCode: 'pk'),
  Countries(name: 'Palau', isoCode: 'pw'),
  Countries(name: 'Palestine', isoCode: 'ps'),
  Countries(name: 'Panama', isoCode: 'pa'),
  Countries(name: 'Papua New Guinea', isoCode: 'pg'),
  Countries(name: 'Paraguay', isoCode: 'py'),
  Countries(name: 'Peru', isoCode: 'pe'),
  Countries(name: 'Philippines', isoCode: 'ph'),
  Countries(name: 'Pitcairn ', isoCode: 'pn'),
  Countries(name: 'Poland', isoCode: 'pl'),
  Countries(name: 'Portugal', isoCode: 'pt'),
  Countries(name: 'Puerto Rico', isoCode: 'pr'),
  Countries(name: 'Qatar', isoCode: 'qa'),
  Countries(name: 'Republic of North Macedonia', isoCode: 'mk'),
  Countries(name: 'Romania', isoCode: 'ro'),
  Countries(name: 'Russia', isoCode: 'ru'),
  Countries(name: 'Rwanda', isoCode: 'rw'),
  Countries(name: 'Saint Barthélemy', isoCode: 'bl'),
  Countries(name: 'Saint Helena', isoCode: 'sh'),
  Countries(name: 'Saint Kitts and Nevis ', isoCode: 'kn'),
  Countries(name: 'Saint Lucia', isoCode: 'lc'),
  Countries(name: 'Saint Martin', isoCode: 'mf'),
  Countries(name: 'Saint Pierre and Miquelon', isoCode: 'pm'),
  Countries(name: 'Saint Vincent and the Grenadines', isoCode: 'vc'),
  Countries(name: 'Samoa', isoCode: 'ws'),
  Countries(name: 'San Marino', isoCode: 'sm'),
  Countries(name: 'Sao Tome and Principe', isoCode: 'sa'),
  Countries(name: 'Senegal', isoCode: 'sn'),
  Countries(name: 'Serbia ', isoCode: 'rs'),
  Countries(name: 'Seychelles', isoCode: 'sc'),
  Countries(name: 'Sierra Leone', isoCode: 'sl'),
  Countries(name: 'Singapore', isoCode: 'sg'),
  Countries(name: 'Sint Maarten', isoCode: 'sx'),
  Countries(name: 'Slovakia', isoCode: 'sk'),
  Countries(name: 'Slovenia', isoCode: 'si'),
  Countries(name: 'Solomon Islands', isoCode: 'so'),
  Countries(name: 'Somalia', isoCode: 'kp'),
  Countries(name: 'South Africa', isoCode: 'za'),
  Countries(
      name: 'South Georgia and the South Sandwich Islands', isoCode: 'gs'),
  Countries(name: 'South Korea', isoCode: 'kr'),
  Countries(name: 'Spain', isoCode: 'es'),
  Countries(name: 'Sri Lanka', isoCode: 'lk'),
  Countries(name: 'Sudan', isoCode: 'sd'),
  Countries(name: 'Suriname', isoCode: 'sr'),
  Countries(name: 'Svalbard and Jan Mayen', isoCode: 'sj'),
  Countries(name: 'Sweden', isoCode: 'se'),
  Countries(name: 'Switzerland', isoCode: 'ch'),
  Countries(name: 'Syrian Arab Republic', isoCode: 'sy'),
  Countries(name: 'Taiwan', isoCode: 'tw'),
  Countries(name: 'Tajikistan ', isoCode: 'tj'),
  Countries(name: 'Tanzania', isoCode: 'tz'),
  Countries(name: 'Thailand', isoCode: 'th'),
  Countries(name: 'Timor-Leste', isoCode: 'tl'),
  Countries(name: 'Togo', isoCode: 'tg'),
  Countries(name: 'Tokelau', isoCode: 'tk'),
  Countries(name: 'Tonga', isoCode: 'to'),
  Countries(name: 'Trinidad and Tobago', isoCode: 'tt'),
  Countries(name: 'Tunisia', isoCode: 'tn'),
  Countries(name: 'Turkey', isoCode: 'tr'),
  Countries(name: 'Turkmenistan', isoCode: 'tm'),
  Countries(name: 'Turks and Caicos Islands', isoCode: 'tc'),
  Countries(name: 'Tuvalu', isoCode: 'tv'),
  Countries(name: 'Uganda', isoCode: 'ug'),
  Countries(name: 'Ukraine', isoCode: 'ua'),
  Countries(name: 'United Arab Emirates', isoCode: 'ae'),
  Countries(
      name: 'United Kingdom of Great Britain and Northern Ireland',
      isoCode: 'gb'),
  Countries(name: 'United States of America', isoCode: 'us'),
  Countries(name: 'Uruguay', isoCode: 'uy'),
  Countries(name: 'Uzbekistan', isoCode: 'uz'),
  Countries(name: 'Vanuatu', isoCode: 'vu'),
  Countries(name: 'Venezuela', isoCode: 've'),
  Countries(name: 'Vietnam', isoCode: 'vn'),
  Countries(name: 'Virgin Islands (British)', isoCode: 'vg'),
  Countries(name: 'Virgin Islands (U.S.)', isoCode: 'vi'),
  Countries(name: 'Wallis and Futuna ', isoCode: 'wf'),
  Countries(name: 'Western Sahara', isoCode: 'eh'),
  Countries(name: 'Yemen', isoCode: 'ye'),
  Countries(name: 'Zambia ', isoCode: 'zm'),
  Countries(name: 'Zimbabwe', isoCode: 'zw'),
  Countries(name: 'Åland Islands', isoCode: 'ax'),
];
