class Timezones {
    String timezeon;
    String name;
  
    Timezones(this.timezeon, this.name);
  
    static List<Timezones> getTimezones() {
      return <Timezones>[
        Timezones('+00:00', 'Africa/Abidjan'),
        Timezones('+00:00', 'Africa/Accra'),
        Timezones('+01:00', 'Africa/Algiers'),
        Timezones('+00:00', 'Africa/Bissau'),
        Timezones('+02:00', 'Africa/Cairo'),
        Timezones('+01:00', 'Africa/Casablanca'),
        Timezones('+02:00', 'Africa/Ceuta'),
        Timezones('+01:00', 'Africa/El_Aaiun'),
        Timezones('+02:00', 'Africa/Johannesburg'),
        Timezones('+03:00', 'Africa/Juba'),

        Timezones('+02:00', 'Africa/Khartoum'),
        Timezones('+01:00', 'Africa/Lagos'),
        Timezones('+02:00', 'Africa/Maputo'),
        Timezones('+00:00', 'Africa/Monrovia'),
        Timezones('+03:00', 'Africa/Nairobi'),
        Timezones('+01:00', 'Africa/Ndjamena'),
        Timezones('+00:00', 'Africa/Sao_Tome'),
        Timezones('+02:00', 'Africa/Tripoli'),
        Timezones('+01:00', 'Africa/Tunis'),
        Timezones('+02:00', 'Africa/Windhoek'),

        Timezones('-09:00', 'America/Adak'),
        Timezones('-08:00', 'America/Anchorage'),
        Timezones('-03:00', 'America/Araguaina'),
        Timezones('-03:00', 'America/Argentina/Buenos_Aires'),
        Timezones('-03:00', 'America/Argentina/Catamarca'),
        Timezones('-03:00', 'America/Argentina/Cordoba'),
        Timezones('-03:00', 'America/Argentina/Jujuy'),
        Timezones('-03:00', 'America/Argentina/La_Rioja'),
        Timezones('-03:00', 'America/Argentina/Mendoza'),
        Timezones('-03:00', 'America/Argentina/Rio_Gallegos'),

        Timezones('-03:00', 'America/Argentina/Salta'),
        Timezones('-03:00', 'America/Argentina/San_Juan'),
        Timezones('-03:00', 'America/Argentina/San_Luis'),
        Timezones('-03:00', 'America/Argentina/Tucuman'),
        Timezones('-03:00', 'America/Argentina/Ushuaia'),
        Timezones('-04:00', 'America/Asuncion'),
        Timezones('-05:00', 'America/Atikokan'),
        Timezones('-03:00', 'America/Bahia'),
        Timezones('-05:00', 'America/Bahia_Banderas'),
        Timezones('-04:00', 'America/Barbados'),

        Timezones('-03:00', 'America/Belem'),
        Timezones('-06:00', 'America/Belize'),
        Timezones('-04:00', 'America/Blanc-Sablon'),
        Timezones('-04:00', 'America/Boa_Vista'),
        Timezones('-05:00', 'America/Bogota'),
        Timezones('-06:00', 'America/Boise'),
        Timezones('-06:00', 'America/Cambridge_Bay'),
        Timezones('-04:00', 'America/Campo_Grande'),
        Timezones('-05:00', 'America/Cancun'),
        Timezones('-04:00', 'America/Caracas'),

        Timezones('-03:00', 'America/Cayenne'),
        Timezones('-05:00', 'America/Chicago'),
        Timezones('-06:00', 'America/Chihuahua'),
        Timezones('-06:00', 'America/Costa_Rica'),
        Timezones('-07:00', 'America/Creston'),
        Timezones('-04:00', 'America/Cuiaba'),
        Timezones('-04:00', 'America/Curacao'),
        Timezones('+00:00', 'America/Danmarkshavn'),
        Timezones('-07:00', 'America/Dawson'),
        Timezones('-07:00', 'America/Dawson_Creek'),

        Timezones('-06:00', 'America/Denver'),
        Timezones('-04:00', 'America/Detroit'),
        Timezones('-06:00', 'America/Edmonton'),
        Timezones('-05:00', 'America/Eirunepe'),
        Timezones('-06:00', 'America/El_Salvador'),
        Timezones('-07:00', 'America/Fort_Nelson'),
        Timezones('-03:00', 'America/Fortaleza'),
        Timezones('-03:00', 'America/Glace_Bay'),
        Timezones('-05:00', 'America/Guayaquil'),
        Timezones('-04:00', 'America/Guyana'),

        Timezones('-03:00', 'America/Halifax'),
        Timezones('-04:00', 'America/Havana'),
        Timezones('-07:00', 'America/Hermosillo'),
        Timezones('-04:00', 'America/Indiana/Indianapolis'),
        Timezones('-05:00', 'America/Indiana/Knox'),
        Timezones('-04:00', 'America/Indiana/Marengo'),
        Timezones('-04:00', 'America/Indiana/Petersburg'),
        Timezones('-05:00', 'America/Indiana/Tell_City'),
        Timezones('-04:00', 'America/Indiana/Vevay'),
        Timezones('-04:00', 'America/Indiana/Vincennes'),

        Timezones('-04:00', 'America/Indiana/Winamac'),
        Timezones('-06:00', 'America/Inuvik'),
        Timezones('-04:00', 'America/Iqaluit'),
        Timezones('-05:00', 'America/Jamaica'),
        Timezones('-08:00', 'America/Juneau'),
        Timezones('-04:00', 'America/Kentucky/Louisville'),
        Timezones('-04:00', 'America/Kentucky/Monticello'),
        Timezones('-04:00', 'America/La_Paz'),
        Timezones('-05:00', 'America/Lima'),
        Timezones('-07:00', 'America/Los_Angeles'),

        Timezones('-03:00', 'America/Maceio'),
        Timezones('-06:00', 'America/Managua'),
        Timezones('-04:00', 'America/Manaus'),
        Timezones('-04:00', 'America/Martinique'),
        Timezones('-05:00', 'America/Matamoros'),
        Timezones('-06:00', 'America/Mazatlan'),
        Timezones('-05:00', 'America/Menominee'),
        Timezones('-05:00', 'America/Merida'),
        Timezones('-08:00', 'America/Metlakatla'),
        Timezones('-05:00', 'America/Mexico_City'),

        Timezones('-02:00', 'America/Miquelon'),
        Timezones('-03:00', 'America/Moncton'),
        Timezones('-05:00', 'America/Monterrey'),
        Timezones('-03:00', 'America/Montevideo'),
        Timezones('-04:00', 'America/Nassau'),
        Timezones('-04:00', 'America/New_York'),
        Timezones('-04:00', 'America/Kentucky/Monticello'),
        Timezones('-04:00', 'America/Nipigon'),
        Timezones('-08:00', 'America/Nome'),
        Timezones('-02:00', 'America/Noronha'),

        Timezones('-05:00', 'America/North_Dakota/Beulah'),
        Timezones('-05:00', 'America/North_Dakota/Center'),
        Timezones('-05:00', 'America/North_Dakota/New_Salem'),
        Timezones('-02:00', 'America/Nuuk'),
        Timezones('-06:00', 'America/Ojinaga'),
        Timezones('-05:00', 'America/Panama'),
        Timezones('-04:00', 'America/Pangnirtung'),
        Timezones('-03:00', 'America/Paramaribo'),
        Timezones('-07:00', 'America/Phoenix'),
        Timezones('-04:00', 'America/Port-au-Prince'),

        Timezones('-04:00', 'America/Port_of_Spain'),
        Timezones('-04:00', 'America/Porto_Velho'),
        Timezones('-04:00', 'America/Puerto_Rico'),
        Timezones('-03:00', 'America/Punta_Arenas'),
        Timezones('-05:00', 'America/Rainy_River'),
        Timezones('-05:00', 'America/Rankin_Inlet'),
        Timezones('-03:00', 'America/Recife'),
        Timezones('-06:00', 'America/Regina'),
        Timezones('-05:00', 'America/Resolute'),
        Timezones('-05:00', 'America/Rio_Branco'),

        Timezones('-03:00', 'America/Santarem'),
        Timezones('-03:00', 'America/Santiago'),
        Timezones('-04:00', 'America/Santo_Domingo'),
        Timezones('-03:00', 'America/Sao_Paulo'),
        Timezones('+00:00', 'America/Scoresbysund'),
        Timezones('-08:00', 'America/Sitka'),
        Timezones('-02:30', 'America/St_John'),
        Timezones('-06:00', 'America/Swift_Current'),
        Timezones('-06:00', 'America/Tegucigalpa'),
        Timezones('-02:00', 'America/Thule'),

        Timezones('-05:00', 'America/Thunder_Bay'),
        Timezones('-07:00', 'America/Tijuana'),
        Timezones('-04:00', 'America/Toronto'),
        Timezones('-07:00', 'America/Vancouver'),
        Timezones('-07:00', 'America/Whitehorse'),
        Timezones('-05:00', 'America/Winnipeg'),
        Timezones('-08:00', 'America/Yakutat'),
        Timezones('-06:00', 'America/Yellowknife'),
        Timezones('+08:00', 'Antarctica/Casey'),
        Timezones('+07:00', 'Antarctica/Davis'),

        Timezones('+10:00', 'Antarctica/DumontDUrville'),
        Timezones('+11:00', 'Antarctica/Macquarie'),
        Timezones('+05:00', 'Antarctica/Mawson'),
        Timezones('-03:00', 'Antarctica/Palmer'),
        Timezones('-03:00', 'Antarctica/Rothera'),
        Timezones('+03:00', 'Antarctica/Syowa'),
        Timezones('+02:00', 'Antarctica/Troll'),
        Timezones('+06:00', 'Antarctica/Vostok'),
        Timezones('+06:00', 'Asia/Almaty'),
        Timezones('+03:00', 'Asia/Amman'),

        Timezones('+12:00', 'Asia/Anadyr'),
        Timezones('+05:00', 'Asia/Aqtau'),
        Timezones('+05:00', 'Asia/Aqtobe'),
        Timezones('+05:00', 'Asia/Ashgabat'),
        Timezones('+05:00', 'Asia/Atyrau'),
        Timezones('+03:00', 'Asia/Baghdad'),
        Timezones('+04:00', 'Asia/Baku'),
        Timezones('+07:00', 'Asia/Bangkok'),
        Timezones('+07:00', 'Asia/Barnaul'),
        Timezones('+03:00', 'Asia/Beirut'),

        Timezones('+06:00', 'Asia/Bishkek'),
        Timezones('+08:00', 'Asia/Brunei'),
        Timezones('+09:00', 'Asia/Chita'),
        Timezones('+08:00', 'Asia/Choibalsan'),
        Timezones('+05:30', 'Asia/Colombo'),
        Timezones('+03:00', 'Asia/Damascus'),
        Timezones('+06:00', 'Asia/Dhaka'),
        Timezones('+09:00', 'Asia/Dili'),
        Timezones('+04:00', 'Asia/Dubai'),
        Timezones('+05:00', 'Asia/Dushanbe'),

        Timezones('+03:00', 'Asia/Famagusta'),
        Timezones('+03:00', 'Asia/Gaza'),
        Timezones('+03:00', 'Asia/Hebron'),
        Timezones('+07:00', 'Asia/Ho_Chi_Minh'),
        Timezones('+08:00', 'Asia/Hong_Kong'),
        Timezones('+07:00', 'Asia/Hovd'),
        Timezones('+08:00', 'Asia/Irkutsk'),
        Timezones('+07:00', 'Asia/Jakarta'),
        Timezones('+09:00', 'Asia/Jayapura'),
        Timezones('+03:00', 'Asia/Jerusalem'),

        Timezones('+04:30', 'Asia/Kabul'),
        Timezones('+12:00', 'Asia/Kamchatka'),
        Timezones('+05:00', 'Asia/Karachi'),
        Timezones('+05:45', 'Asia/Kathmandu'),
        Timezones('+09:00', 'Asia/Khandyga'),
        Timezones('+05:30', 'Asia/Kolkata'),
        Timezones('+07:00', 'Asia/Krasnoyarsk'),
        Timezones('+08:00', 'Asia/Kuala_Lumpur'),
        Timezones('+09:00', 'Asia/Kuching'),
        Timezones('+08:00', 'Asia/Macau'),

        Timezones('+11:00', 'Asia/Magadan'),
        Timezones('+08:00', 'Asia/Makassar'),
        Timezones('+08:00', 'Asia/Manila'),
        Timezones('+03:00', 'Asia/Nicosia'),
        Timezones('+07:00', 'Asia/Novokuznetsk'),
        Timezones('+07:00', 'Asia/Novosibirsk'),
        Timezones('+06:00', 'Asia/Omsk'),
        Timezones('+05:00', 'Asia/Oral'),
        Timezones('+07:00', 'Asia/Pontianak'),
        Timezones('+09:00', 'Asia/Pyongyang'),

        Timezones('+03:00', 'Asia/Qatar'),
        Timezones('+06:00', 'Asia/Qostanay'),
        Timezones('+05:00', 'Asia/Qyzylorda'),
        Timezones('+03:00', 'Asia/Riyadh'),
        Timezones('+11:00', 'Asia/Sakhalin'),
        Timezones('+05:00', 'Asia/Samarkand'),
        Timezones('+09:00', 'Asia/Seoul'),
        Timezones('+08:00', 'Asia/Shanghai'),
        Timezones('+08:00', 'Asia/Singapore'),
        Timezones('+11:00', 'Asia/Srednekolymsk'),

        Timezones('+08:00', 'Asia/Taipei'),
        Timezones('+05:00', 'Asia/Tashkent'),
        Timezones('+04:00', 'Asia/Tbilisi'),
        Timezones('+03:30', 'Asia/Tehran'),
        Timezones('+06:00', 'Asia/Thimphu'),
        Timezones('+09:00', 'Asia/Tokyo'),
        Timezones('+07:00', 'Asia/Tomsk'),
        Timezones('+08:00', 'Asia/Ulaanbaatar'),
        Timezones('+06:00', 'Asia/Urumqi'),
        Timezones('+10:00', 'Asia/Ust-Nera'),

        Timezones('+10:00', 'Asia/Vladivostok'),
        Timezones('+09:00', 'Asia/Yakutsk'),
        Timezones('+06:30', 'Asia/Yangon'),
        Timezones('+05:00', 'Asia/Yekaterinburg'),
        Timezones('+04:00', 'Asia/Yerevan'),
        Timezones('+00:00', 'Atlantic/Azores'),
        Timezones('-03:00', 'Atlantic/Bermuda'),
        Timezones('+01:00', 'Atlantic/Canary'),
        Timezones('-01:00', 'Atlantic/Cape_Verde'),
        Timezones('+01:00', 'Atlantic/Faroe'),

        Timezones('+01:00', 'Atlantic/Madeira'),
        Timezones('+00:00', 'Atlantic/Reykjavik'),
        Timezones('-02:00', 'Atlantic/South_Georgia'),
        Timezones('-03:00', 'Atlantic/Stanley'),
        Timezones('+09:30', 'Australia/Adelaide'),
        Timezones('+10:00', 'Australia/Brisbane'),
        Timezones('+09:30', 'Australia/Broken_Hill'),
        Timezones('+10:00', 'Australia/Currie'),
        Timezones('+09:30', 'Australia/Darwin'),
        Timezones('+08:45', 'Australia/Eucla'),

        Timezones('+10:00', 'Australia/Hobart'),
        Timezones('+10:00', 'Australia/Lindeman'),
        Timezones('+10:30', 'Australia/Lord_Howe'),
        Timezones('+10:00', 'Australia/Melbourne'),
        Timezones('+08:00', 'Australia/Perth'),
        Timezones('+10:00', 'Australia/Sydney'),
        Timezones('+00:00', 'CET'),
        Timezones('+00:00', 'CST6CDT'),
        Timezones('+00:00', 'EET'),
        Timezones('+00:00', 'EST'),

        Timezones('-04:00', 'EST5EDT'),
        Timezones('-01:00', 'Etc/GMT+1'),
        Timezones('-11:00', 'Etc/GMT+11'),
        Timezones('-12:00', 'Etc/GMT+12'),
        Timezones('+02:00', 'Europe/Amsterdam'),
        Timezones('+02:00', 'Europe/Andorra'),
        Timezones('+04:00', 'Europe/Astrakhan'),
        Timezones('+03:00', 'Europe/Athens'),
        Timezones('+02:00', 'Europe/Belgrade'),
        Timezones('+02:00', 'Europe/Berlin'),

        Timezones('+02:00', 'Europe/Brussels'),
        Timezones('+03:00', 'Europe/Bucharest'),
        Timezones('+02:00', 'Europe/Budapest'),
        Timezones('+03:00', 'Europe/Chisinau'),
        Timezones('+02:00', 'Europe/Copenhagen'),
        Timezones('02:00', 'Europe/Dublin'),
        Timezones('+03:00', 'Europe/Helsinki'),
        Timezones('+03:00', 'Europe/Istanbul'),
        Timezones('+02:00', 'Europe/Kaliningrad'),
        Timezones('+03:00', 'Europe/Kiev'),

        Timezones('+03:00', 'Europe/Kirov'),
        Timezones('+01:00', 'Europe/Lisbon'),
        Timezones('+01:00', 'Europe/London'),
        Timezones('+02:00', 'Europe/Luxembourg'),
        Timezones('+02:00', 'Europe/Madrid'),
        Timezones('+02:00', 'Europe/Malta'),
        Timezones('+03:00', 'Europe/Minsk'),
        Timezones('+02:00', 'Europe/Monaco'),
        Timezones('+03:00', 'Europe/Moscow'),
        Timezones('+02:00', 'Europe/Oslo'),

        Timezones('+02:00', 'Europe/Paris'),
        Timezones('+02:00', 'Europe/Prague'),
        Timezones('+03:00', 'Europe/Riga'),
        Timezones('+02:00', 'Europe/Rome'),
        Timezones('+04:00', 'Europe/Samara'),
        Timezones('+04:00', 'Europe/Saratov'),
        Timezones('+03:00', 'Europe/Simferopol'),
        Timezones('+03:00', 'Europe/Sofia'),
        Timezones('+02:00', 'Europe/Stockholm'),
        Timezones('+03:00', 'Europe/Tallinn'),

        Timezones('+02:00', 'Europe/Tirane'),
        Timezones('+04:00', 'Europe/Ulyanovsk'),
        Timezones('+03:00', 'Europe/Uzhgorod'),
        Timezones('+02:00', 'Europe/Vienna'),
        Timezones('+03:00', 'Europe/Vilnius'),
        Timezones('+04:00', 'Europe/Volgograd'),
        Timezones('+02:00', 'Europe/Warsaw'),
        Timezones('+03:00', 'Europe/Zaporozhye'),
        Timezones('+02:00', 'Europe/Zurich'),
        Timezones('+06:00', 'Indian/Chagos'),

        Timezones('+07:00', 'Indian/Christmas'),
        Timezones('+06:30', 'Indian/Cocos'),
        Timezones('+05:00', 'Indian/Kerguelen'),
        Timezones('+04:00', 'Indian/Mahe'),
        Timezones('+05:00', 'Indian/Maldives'),
        Timezones('+04:00', 'Indian/Mauritius'),
        Timezones('+04:00', 'Indian/Reunion'),
        Timezones('+14:00', 'Pacific/Apia'),
        Timezones('+13:00', 'Pacific/Auckland'),
        Timezones('+11:00', 'Pacific/Bougainville'),

        Timezones('+10:00', 'Pacific/Chuuk'),
        Timezones('-05:00', 'Pacific/Easter'),
        Timezones('+11:00', 'Pacific/Efate'),
        Timezones('+13:00', 'Pacific/Enderbury'),
        Timezones('+13:00', 'Pacific/Fakaofo'),
        Timezones('+12:00', 'Pacific/Fiji'),
        Timezones('+12:00', 'Pacific/Funafuti'),
        Timezones('-06:00', 'Pacific/Galapagos'),
        Timezones('-09:00', 'Pacific/Gambier'),
        Timezones('+11:00', 'Pacific/Guadalcanal'),

        Timezones('+10:00', 'Pacific/Guam'),
        Timezones('-10:00', 'Pacific/Honolulu'),
        Timezones('+14:00', 'Pacific/Kiritimati'),
        Timezones('+11:00', 'Pacific/Kosrae'),
        Timezones('+12:00', 'Pacific/Kwajalein'),
        Timezones('+12:00', 'Pacific/Majuro'),
        Timezones('-09:30', 'Pacific/Marquesas'),
        Timezones('+12:00', 'Pacific/Nauru'),
        Timezones('-11:00', 'Pacific/Niue'),
        Timezones('+11:00', 'Pacific/Norfolk'),

        Timezones('+11:00', 'Pacific/Noumea'),
        Timezones('-11:00', 'Pacific/Pago_Pago'),
        Timezones('+09:00', 'Pacific/Palau'),
        Timezones('-08:00', 'Pacific/Pitcairn'),
        Timezones('+11:00', 'Pacific/Pohnpei'),
        Timezones('+12:00', 'Pacific/Port_Moresby'),
        Timezones('-10:00', 'Pacific/Rarotonga'),
        Timezones('-10:00', 'Pacific/Tahiti'),
        Timezones('+12:00', 'Pacific/Tarawa'),
        Timezones('+13:00', 'Pacific/Tongatapu'),

        Timezones('+12:00', 'Pacific/Wake'),
        Timezones('+12:00', 'Pacific/Wallis'),

      ];
    }
  }