class FromCountry {
  String name;
  String isoCode;

  FromCountry(this.name, this.isoCode);

  static List<FromCountry> getFromCountry() {
    return <FromCountry>[
      FromCountry('Afghanistan', 'AF'),
      FromCountry('Albania', 'AL'),
      FromCountry('Algeria', 'DZ'),
      FromCountry('American Samoa', 'AS'),
      FromCountry('Andorra', 'AF'),
      FromCountry('Afghanistan', 'AD'),
      FromCountry('Angola', 'AO'),
      FromCountry('Anguilla', 'AI'),
      FromCountry('Antarctica', 'AQ'),
      FromCountry('Antigua and Barbuda', 'AG'),
      FromCountry('Argentina', 'AR'),
      FromCountry('Armenia', 'AM'),
      FromCountry('Aruba', 'AW'),
      FromCountry('Australia', 'AU'),
      FromCountry('Austria', 'AT'),
      FromCountry('Azerbaijan', 'AZ'),
      FromCountry('Bahamas', 'BS'),
      FromCountry('Bahrain', 'BH'),
      FromCountry('Bangladesh', 'BD'),
      FromCountry('Barbados', 'BB'),
      FromCountry('Belarus', 'BY'),
      FromCountry('Belgium', 'BE'),
      FromCountry('Belize', 'BZ'),
      FromCountry('Benin', 'BJ'),
      FromCountry('Bermuda', 'BM'),
      FromCountry('Bhutan', 'BT'),
      FromCountry('Bolivia', 'BO'),
      FromCountry('Bonaire, Sint Eustatius and Saba', 'BQ'),
      FromCountry('Bosnia and Herzegovina', 'BA'),
      FromCountry('Botswana', 'BW'),
      FromCountry('Bouvet Island', 'BV'),
      FromCountry('Brazil', 'BR'),
      FromCountry('British Indian Ocean Territory', 'IO'),
      FromCountry('Brunei Darussalam', 'BN'),
      FromCountry('Bulgaria', 'BG'),
      FromCountry('Burkina Faso', 'BF'),
      FromCountry('Burundi', 'BI'),
      FromCountry('Cabo Verde ', 'CV'),
      FromCountry('Cambodia', 'CM'),
      FromCountry('Canada', 'CA'),
      FromCountry('Cayman Islands', 'KY'),
      FromCountry('Central African Republic', 'BY'),
      FromCountry('Chad', 'TD'),
      FromCountry('Chile', 'CL'),
      FromCountry('China', 'CN'),
      FromCountry('Christmas Island', 'CX'),
      FromCountry('Colombia', 'CO'),
      FromCountry('Comoros ', 'KM'),
      FromCountry('Congo', 'CD'),
      FromCountry('Cook Islands', 'CK'),
      FromCountry('Costa Rica', 'CR'),
      FromCountry('Croatia', 'HR'),
      FromCountry('Cuba', 'CU'),
      FromCountry('Curaçao', 'CW'),
      FromCountry('Cyprus', 'CY'),
      FromCountry('Czechia', 'CZ'),
      FromCountry('Denmark', 'DK'),
      FromCountry('Djibouti', 'DJ'),
      FromCountry('Dominica ', 'DM'),
      FromCountry('Dominican Republic', 'DO'),
      FromCountry('Ecuador', 'EC'),
      FromCountry('Egypt', 'EG'),
      FromCountry('El Salvador', 'SV'),
      FromCountry('Equatorial Guinea', 'GQ'),
      FromCountry('Equatorial Guinea', 'GQ'),
      FromCountry('Eritrea', 'ER'),
      FromCountry('Estonia', 'EE'),
      FromCountry('Eswatini', 'SZ'),
      FromCountry('Ethiopia', 'ET'),
      FromCountry('Falkland Islands', 'FK'),
      FromCountry('Faroe Islands', 'FO'),
      FromCountry('Fiji', 'FJ'),
      FromCountry('Finland', 'FI'),
      FromCountry('France', 'FR'),
      FromCountry('French Guiana', 'GF'),
      FromCountry('French Polynesia', 'PF'),
      FromCountry('French Southern Territories', 'TF'),
      FromCountry('Gabon', 'GA'),
      FromCountry('Gambia', 'DE'),
      FromCountry('Germany', 'DM'),
      FromCountry('Ghana', 'GH'),
      FromCountry('Gibraltar', 'GI'),
      FromCountry('Greece', 'GR'),
      FromCountry('Greenland', 'GL'),
      FromCountry('Grenada', 'GD'),
      FromCountry('Guadeloupe', 'GP'),
      FromCountry('Guam', 'GU'),
      FromCountry('Guatemala', 'GT'),
      FromCountry('Guernsey', 'GG'),
      FromCountry('Guinea', 'GN'),
      FromCountry('Guinea-Bissau', 'GW'),
      FromCountry('Guyana', 'GY'),
      FromCountry('Haiti', 'HT'),
      FromCountry('Heard Island and McDonald Islands', 'HM'),
      FromCountry('Honduras', 'HN'),
      FromCountry('Hong Kong', 'HK'),
      FromCountry('Hungary', 'HU'),
      FromCountry('Iceland', 'IS'),
      FromCountry('Indonesia', 'ID'),
      FromCountry('Iran', 'IR'),
      FromCountry('Iraq', 'IQ'),
      FromCountry('Ireland', 'IE'),
      FromCountry('Isle of Man', 'IM'),
      FromCountry('Israel', 'IL'),
      FromCountry('Italy', 'IT'),
      FromCountry('Jamaica', 'JM'),
      FromCountry('Japan', 'JP'),
      FromCountry('Jersey', 'JE'),
      FromCountry('Jordan', 'JO'),
      FromCountry('Kazakhstan', 'KZ'),
      FromCountry('Kenya', 'KE'),
      FromCountry('Kiribati', 'KI'),
      FromCountry('North Korea ', 'KP'),
      FromCountry('South Korea', 'KR'),
      FromCountry('Kuwait', 'KW'),
      FromCountry('Kyrgyzstan', 'KG'),
      FromCountry('Laos', 'LA'),
      FromCountry('Latvia', 'LV'),
      FromCountry('Lebanon', 'LB'),
      FromCountry('Lesotho', 'LS'),
      FromCountry('Liberia', 'LR'),
      FromCountry('Libya', 'LY'),
      FromCountry('Liechtenstein', 'LI'),
      FromCountry('Lithuania', 'LT'),
      FromCountry('Luxembourg', 'LU'),
      FromCountry('Macao', 'MO'),
      FromCountry('Madagascar', 'MG'),
      FromCountry('Malawi', 'MW'),
      FromCountry('Malaysia', 'MY'),
      FromCountry('Maldives', 'MV'),
      FromCountry('Mali', 'ML'),
      FromCountry('Malta ', 'MT'),
      FromCountry('Marshall Islands', 'MH'),
      FromCountry('Martinique', 'MQ'),
      FromCountry('Mauritania', 'MR'),
      FromCountry('Mauritius', 'MU'),
      FromCountry('Mayotte', 'YT'),
      FromCountry('Mexico', 'MX'),
      FromCountry('Micronesia', 'FM'),
      FromCountry('Moldova', 'MD'),
      FromCountry('Monaco ', 'MC'),
      FromCountry('Mongolia', 'MN'),
      FromCountry('Montenegro', 'ME'),
      FromCountry('Montserrat', 'MS'),
      FromCountry('Morocco', 'MA'),
      FromCountry('Mozambique', 'MZ'),
      FromCountry('Myanmar', 'NA'),
      FromCountry('Nauru', 'NR'),
      FromCountry('Nepal', 'NP'),
      FromCountry('Netherlands ', 'NL'),
      FromCountry('New Caledonia ', 'NC'),
      FromCountry('New Zealand', 'NZ'),
      FromCountry('Nicaragua', 'NI'),
      FromCountry('Niger', 'NE'),
      FromCountry('Nigeria', 'NG'),
      FromCountry('Niue', 'NU'),
      FromCountry('Norfolk Island', 'NF'),
      FromCountry('North Korea', 'KP'),
      FromCountry('Northern Mariana Islands', 'MP'),
      FromCountry('Norway', 'NO'),
      FromCountry('Oman', 'OM'),
      FromCountry('Pakistan', 'PK'),
      FromCountry('Palau', 'PW'),
      FromCountry('Palestine', 'PS'),
      FromCountry('Panama', 'PA'),
      FromCountry('Mozambique', 'MZ'),
      FromCountry('Myanmar', 'NA'),
      FromCountry('Nauru', 'NR'),
      FromCountry('Nepal', 'NP'),
      FromCountry('Netherlands ', 'NL'),
      FromCountry('New Caledonia ', 'NC'),
      FromCountry('New Zealand', 'NZ'),
      FromCountry('Nicaragua', 'NI'),
      FromCountry('Niger', 'NE'),
      FromCountry('Nigeria', 'NG'),
      FromCountry('Niue', 'NU'),
      FromCountry('Norfolk Island', 'NF'),
      FromCountry('North Korea', 'KP'),
      FromCountry('Northern Mariana Islands', 'MP'),
      FromCountry('Norway', 'NO'),
      FromCountry('Oman', 'OM'),
      FromCountry('Pakistan', 'PK'),
      FromCountry('Palau', 'PW'),
      FromCountry('Palestine', 'PS'),
      FromCountry('Panama', 'PA'),
      FromCountry('Papua New Guinea', 'PG'),
      FromCountry('Paraguay', 'PY'),
      FromCountry('Peru', 'PE'),
      FromCountry('Philippines', 'PH'),
      FromCountry('Pitcairn ', 'PN'),
      FromCountry('Poland', 'PL'),
      FromCountry('Portugal', 'PT'),
      FromCountry('Puerto Rico', 'PR'),
      FromCountry('Qatar', 'QA'),
      FromCountry('Republic of North Macedonia', 'MK'),
      FromCountry('Romania', 'RO'),
      FromCountry('Russia', 'RU'),
      FromCountry('Rwanda', 'RW'),
      FromCountry('Saint Barthélemy', 'BL'),
      FromCountry('Saint Helena', 'SH'),
      FromCountry('Saint Kitts and Nevis ', 'KN'),
      FromCountry('Saint Lucia', 'LC'),
      FromCountry('Saint Martin', 'MF'),
      FromCountry('Saint Pierre and Miquelon', 'PM'),
      FromCountry('Saint Vincent and the Grenadines', 'VC'),
      FromCountry('Samoa', 'WS'),
      FromCountry('San Marino', 'SM'),
      FromCountry('Sao Tome and Principe', 'SA'),
      FromCountry('Senegal', 'SN'),
      FromCountry('Serbia ', 'RS'),
      FromCountry('Seychelles', 'SC'),
      FromCountry('Sierra Leone', 'SL'),
      FromCountry('Singapore', 'SG'),
      FromCountry('Sint Maarten', 'SX'),
      FromCountry('Slovakia', 'SK'),
      FromCountry('Slovenia', 'SI'),
      FromCountry('Solomon Islands', 'SO'),
      FromCountry('Somalia', 'KP'),
      FromCountry('South Africa', 'ZA'),
      FromCountry('South Georgia and the South Sandwich Islands', 'GS'),
      FromCountry('South Korea', 'KR'),
      FromCountry('Spain', 'ES'),
      FromCountry('Sri Lanka', 'LK'),
      FromCountry('Sudan', 'SD'),
      FromCountry('Suriname', 'SR'),
      FromCountry('Svalbard and Jan Mayen', 'SJ'),
      FromCountry('Sweden', 'SE'),
      FromCountry('Switzerland', 'CH'),
      FromCountry('Syrian Arab Republic', 'SY'),
      FromCountry('Taiwan', 'TW'),
      FromCountry('Tajikistan ', 'TJ'),
      FromCountry('Tanzania', 'TZ'),
      FromCountry('Thailand', 'TH'),
      FromCountry('Timor-Leste', 'TL'),
      FromCountry('Togo', 'TG'),
      FromCountry('Tokelau', 'TK'),
      FromCountry('Tonga', 'TO'),
      FromCountry('Trinidad and Tobago', 'TT'),
      FromCountry('Tunisia', 'TN'),
      FromCountry('Turkey', 'TR'),
      FromCountry('Turkmenistan', 'TM	'),
      FromCountry('Turks and Caicos Islands', 'TC'),
      FromCountry('Tuvalu', 'TV'),
      FromCountry('Uganda', 'UG'),
      FromCountry('Ukraine', 'UA'),
      FromCountry('United Arab Emirates', 'AE'),
      FromCountry('United Kingdom of Great Britain and Northern Ireland', 'GB'),
      FromCountry('United States of America', 'US'),
      FromCountry('Uruguay', 'UY'),
      FromCountry('Uzbekistan', 'UZ'),
      FromCountry('Vanuatu', 'VU'),
      FromCountry('Venezuela', 'VE'),
      FromCountry('Vietnam', 'VN'),
      FromCountry('Virgin Islands (British)', 'VG'),
      FromCountry('Virgin Islands (U.S.)', 'VI'),
      FromCountry('Wallis and Futuna ', 'WF'),
      FromCountry('Western Sahara', 'EH'),
      FromCountry('Western Sahara', 'EH'),
      FromCountry('Yemen', 'YE'),
      FromCountry('Zambia ', 'ZM'),
      FromCountry('Zimbabwe', 'ZW'),
      FromCountry('Åland Islands', 'AX'),
    ];
  }
}
